Document: tas
Title: Debian tas Manual
Author: <insert document author here>
Abstract: This manual describes what tas is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tas/tas.sgml.gz

Format: postscript
Files: /usr/share/doc/tas/tas.ps.gz

Format: text
Files: /usr/share/doc/tas/tas.text.gz

Format: HTML
Index: /usr/share/doc/tas/html/index.html
Files: /usr/share/doc/tas/html/*.html
